### ISSUE TITLE
Error while requesting data

### ISSUE THREAD

**Issue by SarvagyaVaish** [ryanj/eventbrite-client.rb#1]
Hi, 
## I am running the following script in ruby:

require 'eventbrite-client'
eb_auth_tokens = { app_key:  'my-app-key',
                   user_key: 'my-user-key'}
eb_client = EventbriteClient.new(eb_auth_tokens)
response = eb_client.user_list_events()
## print response

I keep getting the following error.
## Also, i noticed I only get the error when there is some data to be returned. If for example there are no events being returned, then there would be no error.

/home/svaish3/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych.rb:203:in `parse': (<unknown>): found unexpected ':' while scanning a plain scalar at line 1 column 547 (Psych::SyntaxError)
    from /home/svaish3/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych.rb:203:in`parse_stream'
    from /home/svaish3/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych.rb:151:in `parse'
    from /home/svaish3/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/psych.rb:127:in`load'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/crack-0.1.8/lib/crack/json.rb:12:in `parse'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/httparty-0.7.8/lib/httparty/parser.rb:116:in`json'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/httparty-0.7.8/lib/httparty/parser.rb:136:in `parse_supported_format'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/httparty-0.7.8/lib/httparty/parser.rb:103:in`parse'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/httparty-0.7.8/lib/httparty/parser.rb:66:in `call'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/httparty-0.7.8/lib/httparty/request.rb:217:in`parse_response'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/httparty-0.7.8/lib/httparty/request.rb:189:in `handle_response'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/httparty-0.7.8/lib/httparty/request.rb:71:in`perform'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/httparty-0.7.8/lib/httparty.rb:390:in `perform_request'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/httparty-0.7.8/lib/httparty.rb:342:in`get'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/eventbrite-client-0.1.0/lib/eventbrite-client.rb:34:in `method_request'
    from /home/svaish3/.rvm/gems/ruby-1.9.3-p194/gems/eventbrite-client-0.1.0/lib/eventbrite-client.rb:42:in`method_missing'
    from EventBriteScraper.rb:9:in `<main>'

**Comment by ryanj** [comment]
Hi Sarvagya,
Thanks for filing this issue, and including a stack trace.  

It looks like there is a problem with the format of the API's JSON data, or possibly a bug in 'psych'.
I don't think I can patch this issue from within this codebase, since this project is not responsible for generating or parsing any of the JSON data.

I couldn't reproduce this issue in my local dev environment either.  I would recommend trying a different JSON parser, or  reporting this issue to Eventbrite's API team (api @ eventbrite.com).

**Comment by nickgrim** [comment]
I had this same problem, with a similar test file. The bug appears to be in Psych, and I fixed it by adding:

```
YAML::ENGINE.yamler = 'syck'
```

near the top of my program.

(Inspiration from: http://stackoverflow.com/questions/4980877/rails-error-couldnt-parse-yaml)

**Comment by ryanj** [comment]
I never ran into this issue because I was using HTTParty+crack to handle the JSON.
http://railstips.org/blog/archives/2009/04/01/crack-the-easiest-way-to-parse-xml-and-json/

It sounds like the Psych YAML parser might get the job done as well, but only when configured to use the older (unmaintained) 'syck' YAML engine. :(

@nickgrim Thanks for the suggestion and the link!

**Comment by ryanj** [comment]
I've updated the requirements to include HTTParty 0.8+, which should fix this issue for everyone - no additional config required.
